[package]
name = "brainfuck-generator"
version = "0.2.1"
edition = "2024"
authors = [ "Xanthorrhizol <xanthorrhizol@proton.me>" ]
description = "Akka actor"
repository = "https://github.com/Xanthorrhizol/actor"
readme = "README.md"
license = "MIT"
keywords = ["brainfuck", "syusuk"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
structopt = "0.3.26"
toml = "1.1.2"
