site_name: Brainfuck Generator
site_url: https://xanthorrhizol.github.io/brainfuck-generator/
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ko
          name: 한국어
          build: true

nav:
  - index.md
  - quickstart.md
  - config.md
  - api.md
  - encoding.md
